### ISSUE TITLE
No automatic retina mode for matplotlib

### ISSUE THREAD

**Issue by DanielVF** [marimo-team/marimo#3793]
### Describe the bug

When I create a plot with mathplotlib, the resolution of the resulting image is noticeably worse than the code and text around it. In Jupyter notebook, there is retina mode that up resolutions charts when on a high DPI monitor.

I could not find documentation on how to do this in Marimo. Obviously it would be nice if importing matplotlib made whatever changes need to be done happen automatically.

<img width="440" alt="Image" src="https://github.com/user-attachments/assets/f2142b89-bb0a-4574-a095-837025c6f292" />

### Environment

<details>
{
  "marimo": "0.11.4",
  "OS": "Darwin",
  "OS Version": "24.1.0",
  "Processor": "arm",
  "Python Version": "3.13.1",
  "Dependencies": {
    "click": "8.1.8",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.7",
    "narwhals": "1.26.0",
    "packaging": "24.2",
    "psutil": "7.0.0",
    "pygments": "2.19.1",
    "pymdown-extensions": "10.14.3",
    "pyyaml": "6.0.2",
    "ruff": "0.9.6",
    "starlette": "0.45.3",
    "tomlkit": "0.13.2",
    "typing-extensions": "missing",
    "uvicorn": "0.34.0",
    "websockets": "14.2"
  },
  "Optional Dependencies": {
    "pandas": "2.2.3"
  },
  "Experimental Flags": {}
}
</details>

### Code to reproduce

```
import marimo as mo
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


x = np.random.rand(27)
y = 20 - np.linspace(2,20,27) * x
df = pd.DataFrame({'x':x, 'y':y})
plt.scatter(df.x, df.y)
```

**Comment by mscolnick** [comment]
We don't do anything automatically, but you can set this yourself with 

```python
plt.rcParams["figure.dpi"] = 250
plt.plot([1, 2])
```

**Comment by mscolnick** [comment]
Closing this given the solution above

**Comment by DanielVF** [comment]
Appreciate the tip.

**Comment by DanielVF** [comment]
Note that changing the DPI  and figure size does not actually fix the issue. 

<img width="368" alt="Image" src="https://github.com/user-attachments/assets/295705d5-e128-4169-979e-45e1d684bc36" />

Changing the DPI increases the number of pixels rendered into the image, but the image then increases in size, thus making a larger, just as blurry image.

<img width="665" alt="Image" src="https://github.com/user-attachments/assets/e3d74874-8de3-4ad8-895d-ec2715ba1032" />

**Comment by DanielVF** [comment]
If I carefully set the figure size so large that the image is resized down to fit in the width, I can get a workable graph. This does constrain the sizes of figures I can work with, and is a bit of an ugly hack.

<img width="1155" alt="Image" src="https://github.com/user-attachments/assets/42512732-702e-4d1a-ba56-03c2ae5e0cbd" />

**Comment by mscolnick** [comment]
@DanielVF, curious if there is something marimo can do? does Jupyter do something different?

**Comment by dahakawang** [comment]
Hey @mscolnick , I met the same issue here. It looks like the besides tuning that `rcParams`, the other thing we're missing here is to also tell marimo frontend to render this image, perhaps 1/2 of its original size, on a HiDPI screen.

Not neccearily suggest it's the only solution, but it seems like in Jupyter when we have `%config InlineBackend.figure_format = 'retina'`, it does so for the user automatically:


<img width="731" alt="Image" src="https://github.com/user-attachments/assets/18ff6c9a-d528-4e12-b400-9cdac54a8292" />

**Comment by dahakawang** [comment]
I'm not familiar with their code base at all -- all are based purely on my observation.

But here's [an issue years ago for the same issue for Jupyter](https://github.com/jupyterlab/jupyterlab/issues/1903), it looks to me that with that `retina` config turned on the "backend" knows all the implication associated with it (telling matplotlib to render more pixels, and telling UI what the preferred rendered size would be,etc). And then there's this "frontend" piece that, given this knowledge, knows it has to use the preferred size instead of the intrinic one, [seen from the PR](https://github.com/jupyterlab/jupyterlab/pull/1924/commits/b7630e648666692058a9c845c6079e51b09cf983) that come with that issue.

**Comment by dahakawang** [comment]
Note sure if I'm 100% right here, but [this](https://github.com/ipython/ipython/blob/5835a76e1eb6c528c0d7ffba0ee808036ad064ac/IPython/core/pylabtools.py#L129-L138) and [this](https://github.com/ipython/ipython/blob/978324813ce6a4a39156c549436b89eb22944038/IPython/core/display.py#L1054-L1055) seems to be part of the trick Jupyter team has done on the "backend", looks similar to what I have guessed the above.

**Comment by sghng** [comment]
Same problem here, also want to add that when plotting with HiDPI, in presentation mode, the graph would over flow the screen and I need to use scroll bar to see the whole thing

**Comment by profConradi** [comment]
Same problem also here. I would like to migrate some of my mathematics visualizations from Jupyter to Marimo, and I need retina mode to have an appropriate quality of my plots.

**Comment by mscolnick** [comment]
@profConradi how are you displaying your plots? can you share your code? this issue was fixed/closed, but maybe a missing edge case.

**Comment by profConradi** [comment]
@mscolnick thank you so much for your reply. I use scatter plots with 10E7 dots or more. Today I've done some accurate testing and I confirm the issue is solved, it was my fault, sorry! The good news is I'm migrating to Marimo from Jupyter!

**Comment by floringogianu** [comment]
Automatic retina mode broke when moving from 0.23.1 to 0.23.2 and it's still an issue in 0.23.8, I just checked all versions.

I strongly suspect it is related to issue https://github.com/marimo-team/marimo/issues/9124, pr https://github.com/marimo-team/marimo/pull/9144

**Comment by floringogianu** [comment]
@mscolnick maybe we can reopen the issue? Should I instead create a new one? Thanks!

**Comment by mscolnick** [comment]
@floringogianu I've reopened. Thanks for flagging

**Comment by floringogianu** [comment]
Not sure why this was marked as completed, it is still a bug as of `v0.23.14`
