### ISSUE TITLE
vim keybindings: pressing `.` is inconsistent

### ISSUE THREAD

**Issue by MarcoGorelli** [marimo-team/marimo#4243]
### Describe the bug

This:

![Image](https://github.com/user-attachments/assets/09c35681-1319-4edd-bc20-2e091047c7ee)

In Vim, `.` is supposed to repeat the latest command

Here, I did:
```
^ c e polars ESC j ^ . j ^ .
```
The first time, `.` did indeed repeat the previous command. But the second time, it just deleted the whole line

### Environment

<details>

```
{
  "marimo": "0.11.26",
  "OS": "Linux",
  "OS Version": "5.15.167.4-microsoft-standard-WSL2",
  "Processor": "x86_64",
  "Python Version": "3.12.8",
  "Binaries": {
    "Browser": "--",
    "Node": "v20.18.0"
  },
  "Dependencies": {
    "click": "8.1.8",
    "docutils": "0.21.2",
    "itsdangerous": "2.2.0",
    "jedi": "0.19.2",
    "markdown": "3.7",
    "narwhals": "1.32.0",
    "packaging": "24.2",
    "psutil": "7.0.0",
    "pygments": "2.19.1",
    "pymdown-extensions": "10.14.3",
    "pyyaml": "6.0.2",
    "ruff": "0.11.2",
    "starlette": "0.46.1",
    "tomlkit": "0.13.2",
    "typing-extensions": "4.12.2",
    "uvicorn": "0.34.0",
    "websockets": "15.0.1"
  },
  "Optional Dependencies": {
    "duckdb": "1.3.0.dev1738",
    "pandas": "2.2.3",
    "polars": "1.26.0"
  },
  "Experimental Flags": {}
}

```

</details>

**Comment by bulletmark** [comment]
Same thing happens for me on Arch Linux + marimo version 0.11.28. If I change something on a line then I can use `.` once more on that line only. 3rd and subsequent `.` just delete a character. Only seems to happen for change operators, e.g. `dw` repeats correctly.

**Comment by bulletmark** [comment]
Actually the more you use it, the more you find `.` is very busted. E.g. insert "123<del>" then repeat this and "123" gets inserted, not "12". There are many other combinations that fail also.

**Comment by mscolnick** [comment]
@bulletmark we use https://github.com/replit/codemirror-vim, which is a port of [codemirror.vim demo](https://codemirror.net/5/demo/vim.html). So it is possible these issues could exist in there, but they unfortunately don't have a playground to test it out.

**Comment by bulletmark** [comment]
I tested new version 0.12.2 for all the issues raised here by the OP and by myself (including issue #4351) and everything seems fixed now so I suggest this issue can be closed. Great work!

@mscolnick FYI, actually  [replit/codemirror-vim](https://github.com/replit/codemirror-vim) does has a reference playground of the master branch at https://raw.githack.com/replit/codemirror-vim/master/dev/web-demo.html

**Comment by mscolnick** [comment]
Ah thanks for the pointer, will use that as the "what good should look like".

**Comment by MarcoGorelli** [comment]
I'm still seeing the exact same issue on Marimo 0.13.0, running on Chrome - any idea what the issue might be?

**Comment by bulletmark** [comment]
@MarcoGorelli I could 100% reproduce the exact example issue you show above but since 0.12.2, and including current version 0.13.0, that issue and all the others I quoted above are fixed for me, at least running on Arch Linux.
